server:
  port: 8080

spring:
  application:
    name: accounts

  profiles:
    active: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=accounts
    username: postgres
    password: Rishabh@123l

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

  config:
    import: optional:configserver:http://localhost:8071/

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
